title: Maeghan Sill
logo: "assets/img/Maeghan Profile Picture.png"
description: Inquisitive, Communicative, Passionate. Leveraging a background in education and learning analytics skills to improve schools in America.  
theme: jekyll-theme-minimal
