title: Maeghan Sill
logo: "assets/img/Maeghan Profile Picture.png"
description: Inquisitive, Communicative, Passionate. Leveraging a background in education along with learning analytics skills to improve schools.  
theme: jekyll-theme-minimal
