title: Maeghan Sill
logo: "assets/img/Maeghan Profile Picture.png"
description: Inquisitive, communicative, and passionate analyst leveraging a background in education and technical skill in learning analytics to improve schools in America.  
theme: jekyll-theme-minimal
