title: Maeghan Sill
logo: "assets/img/Maeghan Profile Picture.png"
description: Inquisitive and Communicative
description: Using data analysis to improving public schools and education policy in the United States. 
theme: jekyll-theme-minimal
